version: "3.8"
services:
  vouch-proxy:
    build:
      context: .
      dockerfile: Dockerfile-local
    volumes:
      - .:/go/src/github.com/vouch/vouch-proxy/
    # ports:
    #   - "9090:9090"
  podinfo:
    image: "stefanprodan/podinfo:latest"
    # ports:
    #   - "9898:9898"
  nginx:
    image: "nginx:stable"
    volumes:
      - ./local/nginx/:/etc/nginx/
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - "vouch-proxy"
      - "podinfo"
