FROM golang:1.14

RUN mkdir -p /go/src/github.com/vouch/vouch-proxy
WORKDIR /go/src/github.com/vouch/vouch-proxy

COPY . .

RUN ./do.sh goget
RUN ./do.sh gobuildstatic # see `do.sh` for vouch-proxy build details
RUN ./do.sh install

RUN go get -u github.com/cosmtrek/air

ENTRYPOINT ["air"]